test = {   'name': 'q4ai2',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> answer[0].shape == (5900, 10)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> answer[1].shape == (5900,)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> answer[2].shape == (295, 10)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> answer[3].shape == (295,)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> answer2[0].shape == (4528, 10)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> answer2[1].shape == (4528,)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
