test = {   'name': 'q4ai3',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> X_train.shape = (1986, 5)\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> y_train.shape == (1986,)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> X_val.shape == (281, 5)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> y_val.shape == (281,)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
