test = {   'name': 'q4',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> abs_loss(1, 1)\n0', 'hidden': False, 'locked': False},
                                   {'code': '>>> abs_loss(-2, 1)\n3', 'hidden': False, 'locked': False},
                                   {'code': '>>> abs_loss(2, 1)\n1', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.sum((squared_loss(np.array([5, 6]), np.array([1, 1])) - np.array([16, 25]))**2)\n0', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
