test = {   'name': 'q1a',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> np.isclose(x_bar, 19.78594262295082)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(y_bar, 2.9982786885245898)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(std_x, 8.8841505777711323)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(std_y, 1.3807999538298954)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(r) == np.float64\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(r, 0.67573410921136412)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
