test = {   'name': 'q1b',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> np.isclose(lr_avg_loss(np.array([0, 0]), X_intercept_train, Y_train), 0.6931471805599453)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> np.isclose(lr_avg_loss([-13.75289919, 0.92881284],\n...                    X_intercept_train, Y_train),\n...            0.31238592774374596)\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
