test = {   'name': 'q1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> list(X_train.shape) == [455, 12]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> list(X_holdout.shape) == [51, 12]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> list(Y_train.shape) == [455, ]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> list(Y_holdout.shape) == [51, ]\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
