test = {   'name': 'q8',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': ">>> run_linear_regression_test(lm.LinearRegression(fit_intercept=True), process_data_fm, 200000, 'cook_county_train.csv', None, False)\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> run_linear_regression_test(lm.LinearRegression(fit_intercept=True), process_data_fm, 240000, 'cook_county_train.csv', None, False)\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> run_linear_regression_test(lm.LinearRegression(fit_intercept=True), process_data_fm, 280000, 'cook_county_train.csv', None, False)\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
